resolver: lts-10.3
packages:
- .
- location: https://github.com/karshan/money-ihaskell/archive/f7e5e10c04c3050457b916caed4fd5ee044ec0b1.zip
  extra-dep: true
- location: https://github.com/karshan/protolude/archive/5c83a823a4c4e176cd6524f44edef454da1718dd.zip
  extra-dep: true
extra-deps: [acid-state-0.14.3]
flags: {}
extra-package-dbs: []
