resolver: lts-10.3
packages:
- .
- location: https://github.com/karshan/protolude/archive/5c83a823a4c4e176cd6524f44edef454da1718dd.zip
  extra-dep: true
extra-deps:
- acid-state-0.14.3
flags: {}
extra-package-dbs: []
